### ISSUE TITLE
Storing User login AuthToken info in SessionStorage

### ISSUE THREAD

**Issue by bernardphua** [fullstackhero/blazor-starter-kit#104]
Not sure why the current implementation store the User's AuthToken , RefreshToken, and login details  in the Local Storage. This seems to be insecure and another person using the same computer may be able to access to a user account if he/she forgotten to logout.

I would think the user 's login info like AuthToken and RefreshToken should be stored in the Session Storage instead. For user preference settings, it should be persist into the database and reload from backend when user login. 

![image](https://user-images.githubusercontent.com/46226572/118594677-67608900-b7dc-11eb-8417-6c177961ef75.png)

**Comment by chhinsras** [comment]
It should be stored on database for security purpose. maybe you could contribue the code.

**Comment by neozhu** [comment]
Consider using Windows authentication. If running intranet environment of the company.

**Comment by unchase** [comment]
You can use your own custom local storage (DB or another...), just implement `ILocalStorageService` and use it in DI.

**Comment by unchase** [comment]
In addition, session storage does not store information between browser tabs.

**Comment by bernardphua** [comment]
I think it's right that sensitive info in session storage should not be accessible across diff browser tabs.

**Comment by unchase** [comment]
In this implementation of Local Storage (in BlazorHero) there is tokens deletion when we **LogOut**. So it's our problem if we didn't logout after working with application.

Moreover the token's data should be available between tabs, since we, having logged in, can open different pages on different tabs. And we don't want a new token to be generated in each tab.
