### ISSUE TITLE
Possible bug on UserService.cs

### ISSUE THREAD

**Issue by fabiofastech** [fullstackhero/blazor-starter-kit#204]
**Describe the bug**
in the role management for users, an HTTP Status 500 may appear, The error comes from GetRolesAsync of UserService.cs:
System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.

**To Reproduce**
1. Access with Administrator user
2. Go to Users
3. Select Actions -> Manage Roles
4. See error in log

To eliminate the problem my solution is:
1) Add "MultipleActiveResultSets = true" to the connection string
2) modify the GetRolesAsync method (in UserService.cs) as follows:

```c#
public async Task <IResult <UserRolesResponse>> GetRolesAsync (string userId)
        {
            var viewModel = new List <UserRoleModel> ();
            var user = await _userManager.FindByIdAsync (userId);
            foreach (var role in _roleManager.Roles.ToList())   // Add .ToList() in this point!
            {
                var userRolesViewModel = new UserRoleModel
...
```

**Comment by iammukeshm** [comment]
Hi,  This was already fixed in the newer codebase. Are you using the nugget package by any chance? I will be publishing a newer version of the package in a few days. 

Attaching a screenshot of the change,
![image](https://user-images.githubusercontent.com/31455818/123417237-26c30f00-d5d5-11eb-9737-c727f2dd8ce6.png)
