### ISSUE TITLE
Change Logos

### ISSUE THREAD

**Issue by buda56** [fullstackhero/blazor-starter-kit#209]
It would be nice if you could swap out the logos with your own in a more simpler manner than having to change them to SVG format

**Comment by iammukeshm** [comment]
You really dont have to use svgs. Even PNGs are fine. You can refer to https://github.com/iammukeshm/cowin/blob/master/cowin/wwwroot/index.html - Line 61
https://github.com/iammukeshm/cowin/blob/master/cowin/Shared/MainLayout.razor - Line 8

I used a png to replace the logo instead of svgs..I hope this answers your query.

**Comment by Zigimun** [comment]
How to change the Browser tab logo?

Cant find the code :(

**Comment by michaelrinderle** [comment]
@Zigimun it's called a favicon.
