### ISSUE TITLE
"BlazorHeroUser" in "Infrastructure".  Is this correct approach?

### ISSUE THREAD

**Issue by Gopichandar** [fullstackhero/blazor-starter-kit#248]
Description:
Just getting started with this and I have started creating the entity and soon realized there seems to be some issue in the way we placed the "IdentityUser" class.  If I want to create an entity in the "Domain" library mapped to IdentityUser, there seems to be no way.  

Since we have "BlazorHeroUser" in "Infrastructure", we are not able to refer users to any Entity which should not be the case I hope.

Can someone point me Is there a way?

**Comment by CocoDico78** [comment]
I believe you would do the same as what is done for `IChatHistory`. Whenever you want to refer to a user, add an interface `IXXXUser` which you can refer to from your entities/models. Then have `BlazorHeroUser` implement that interface. Also edit `BlazorHeroContext` so that tables are correctly created for your new class.

I'm also very new to this but I think the rationale of this is that identity management is not directly handled by EF, hence users are not just one table among others and are treated differently. Anyone else?

**Comment by Gopichandar** [comment]
Thanks for the suggestions @CocoDico78 , But I feel "IChatHistory" case is different where we have direct access to context itself in "Infrastructure". 

Consider a case we have "CreatedBy" in "AuditableEntity" that has "UserId",  I want to somehow map this as "FirstName, Lastname" for the client to view in UI on "Application" layer.   Now, I have no access to get the user info with the Id, not having access to usermanager, dbcontext for Specification.  Got stuck here.

**Comment by CocoDico78** [comment]
> "IChatHistory" case is different where we have direct access to context itself in "Infrastructure"

`IChatHistory` is actually defined in the `Application`project, not the `Infrastructure` project. And notice still how the `Client` application still manages to display chat user name in the `Chat.razor` component. This is sent by the server as a `ChatHistoryResponse` or `ChatUserResponse`. I'm sorry I still can't _explain_ why it's made this way, at least I'm trying to mimic what's already done 🤷
