### ISSUE TITLE
wss://localhost:44398/signalRHub 404

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#259]
![image](https://user-images.githubusercontent.com/1549611/127788885-e268bbf6-4105-40bd-a727-f83d317f3605.png)

**Comment by chrisgate** [comment]
???

**Comment by neozhu** [comment]
I don't know, can you run it without error?

**Comment by iammukeshm** [comment]
I have not yet tested this with 6.0 previews. Probably some change there.

**Comment by neozhu** [comment]
weirdly, 
I did not change to 6.0 in this project.
but I just install 6.0 preview-6 SDK.

**Comment by urmatgit** [comment]
![Uploading blazorHero.jpg…]()

**Comment by urmatgit** [comment]
![IMG_20210804_130027_096](https://user-images.githubusercontent.com/5357178/128162543-22e09a03-4115-40ff-981b-8c90c478a72b.jpg)

**Comment by urmatgit** [comment]
![IMG_20210804_130354_933](https://user-images.githubusercontent.com/5357178/128163039-760c6770-2fab-4825-a757-08d344ae690c.jpg)

**Comment by iammukeshm** [comment]
Please retest with the newer codebase

**Comment by BunkBadger** [comment]
We encountered this error as well. This only seems to occur when using IIS. It does not seem to occur using Kestrel. From what I can tell SignalR is still functional after the error has thrown. 

This issue seems to have begun when SignalR authentication was introduced in commit: https://github.com/blazorhero/CleanArchitecture/commit/45d6e675750a5138b40aa3a3c42bc89c431442a6 
Release 2.2 does not seem to have this issue.
