### ISSUE TITLE
How do i update my production or almost production project when the template have new update #Curious

### ISSUE THREAD

**Issue by chrisgate** [fullstackhero/blazor-starter-kit#262]
How do i update my production or almost production project when the template have new updates #Curious

Cheers to the team!

**Comment by chrisgate** [comment]
@iammukeshm mentioned this **"I have already implemented SingalR updates in the dashboard where the data gets updated live"** on issue [https://github.com/blazorhero/CleanArchitecture/issues/260](url) 
And i am wondering how i can bring it in seamlessly?

**Comment by iammukeshm** [comment]
Since blazorHero is a template project, you can add your project's remote URL pointing to blazorHero git. And then pull the changes. Yes, there will be a couple of merge conflicts...Fix them and merge...Try it with a copy of your repository first.

You can refer - https://stackoverflow.com/questions/56577184/github-pull-changes-from-a-template-repository

**Comment by chrisgate** [comment]
@iammukeshm  Thank you as always!
