### ISSUE TITLE
Question: Dependency Injection?

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-starter-kit#37]
This is purely a question - I cannot for the life of me see where/how _userManager or _snackBar for example get injected in the partial class for say RegisterUserModal.razor.cs

Is it the `WebAssemblyHostBuilderExtensions.cs`?

Please let me know so I can sleep.... :-)

![image](https://user-images.githubusercontent.com/40014477/111955486-84eadc80-8b24-11eb-8add-8f7431202000.png)

**Comment by iammukeshm** [comment]
All the DIs are done at the _Imports.razor pages so that it's accessible throughout all components and we could save quite a lot of code lines.

You can find the _Imports.razor under the Blazor Client project (root). I hope this clears your question.

Any suggestions/feedbacks regarding BlazorHero? 

![image](https://user-images.githubusercontent.com/31455818/111956360-b22d8f80-8b10-11eb-9894-7636e4d5b44f.png)

**Comment by 274188A** [comment]
ah! - perfect thanks.  Possibly better to not do it this way as it injects unnecessarily some services but I'm being picky
