### ISSUE TITLE
Permission Policy Registering Issue

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#44]
When we try to add permission beside view create edit delete.
For example, ViewDashboard claim, in the blazor client, the current code won't accumulate. 

`
            builder
                .Services
                .AddAuthorizationCore(options =>
                {
                    foreach (var permissionModule in PermissionModules.GetAllPermissionsModules())
                    {
                        RegisterPermissionClaimPolicyByModule(options, permissionModule);
                    }
                }) `

I tried the registering code inside server side extension. But it won't work.

**Comment by iammukeshm** [comment]
GetAllPermissionsModule was just a helper method to reduce code lines for CRUD Scenarios. You would have to write your own implementation for Custom Claims.

In the below screenshots, I tried to add a permission claim for Chat Functionality. You can see that you have to seed it to the database first, for the particular user role, then add it in the role controller as well, so that it actually is included in the list. I will commit my sample code for your reference to the main branch.

![image](https://user-images.githubusercontent.com/31455818/112703834-5a02de80-8ebe-11eb-9ee6-57dd7b51b4c6.png)

![devenv_NDObUZNXzW](https://user-images.githubusercontent.com/31455818/112703863-79017080-8ebe-11eb-8a02-f5114af9275c.jpg)

**Comment by iammukeshm** [comment]
Do close the issue, if it's okay from your side, cheers!

**Comment by chhinsras** [comment]
Actually, the below is written for api side, which is working great. I think it should be used for client side as well. I try but it does not work. Can you check this. It is basically read all property (permission) in the permission class.

`public static void GetPermissions(this List<RoleClaimsResponse> allPermissions, Type policy, string roleId)
        {
            FieldInfo[] fields = policy.GetFields(BindingFlags.Static | BindingFlags.Public);
            foreach (FieldInfo fi in fields)
            {
                allPermissions.Add(new RoleClaimsResponse { Value = fi.GetValue(null).ToString(), Type = ApplicationClaimTypes.Permission });
            }
        }
`

**Comment by chhinsras** [comment]
Any update on this?

**Comment by chhinsras** [comment]
Here is workable.

```
RegisgterPermissionClaimPolicyByModule(options, typeof(Permissions.Products));
            RegisgterPermissionClaimPolicyByModule(options, typeof(Permissions.Brands));
```
