### ISSUE TITLE
[Question] Server Side Permission Policy Provider 

### ISSUE THREAD

**Issue by RHaughton** [fullstackhero/blazor-starter-kit#59]
Hi Mukesh,

I just added permission based policy to the server side. 
But whatever I do I get unauthorized even with the admin role.

I added the PermissionAuthorizationHandler and the PermissionPolicyProvider to tthe server Api project but I don't see where you use them. I assume it should be in the startup class.

Thanks for your help.

**Comment by iammukeshm** [comment]
1. Add Permissions to the Static Constant Class, BlazorHero.CleanArchitecture.Shared.Constants.Permission - `public const string Users = "Users";` is an example. 
2. The `GeneratePermissionsForModule` method will generate the required permissions strings for you, `Create,View,Edit,Delete`.
3. Once you add a new permission, you need to manually ensure that the ADMIN Role has this permission, since this is a role-based permission. `BlazorHero.CleanArchitecture.Infrastructure.DatabaseSeeder` is where the seeding happens when the application starts.
4. Under the `AddAdministrator` method , somewhere around the 80th line, add this `await _roleManager.GeneratePermissionClaimByModule(adminRole, PermissionModules.xxxxx);`. This adds the new permission to admin role. Once the app is started, check your db - RoleClaims table to check if this permission exists.

That's for the backend. Now for the frontend to receive this newly updated permission list, you need to make some changes on the Controller Service level.
1. ` BlazorHero.CleanArchitecture.Infrastructure.Services.Identity` is the required service.
2. Line #76 is where you would want to add a `allPermissions.GetPermissions(typeof(Permissions.xxxx), roleId);`

This should get your permissions working. Similarly, you can add the attributes as well when required. `[Authorize(Policy = Permissions.Users.Edit)]`
