### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#71]
I was considering using Blazorboilerplate. But, due to inadequate documentation for **newbies**, the project quickly becomes quite complex.  We then have to spend a lot to time figuring things out. 
I am hoping that the documentation in BLAZORHERO keeps pace with the project and we can follow it, step by step.
For example, I need to use Sendgrid in my project. I am used to using it in different way and would be grateful for steps on how to configure SENDGRID in BLAZORHERO. I don't even know which project to add the Sendgrid NUGET package into, how sad is that?  :) :)
Many thanks
Luke

**Comment by iang0ld** [comment]
I agree.

I think the main benefit of BlazorBoilerplate is IdentityServer Interface and oAuth2. I also looked at abp.io but it too is heavy.

But nothing seems as straightforward as Clean Architecture.

I was looking at Jason Taylors Clean Architecture and adding Blazor, which this project has more or less done. https://github.com/jasontaylordev/CleanArchitecture

Yours
Ian

From: Duelbat ***@***.***>
Sent: Sunday, 18 April 2021 5:56 PM
To: blazorhero/CleanArchitecture ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blazorhero/CleanArchitecture] Documentation (#71)


I was considering using Blazorboilerplate. But, due to inadequate documentation for newbies, the project quickly becomes quite complex. We then have to spend a lot to time figuring things out.
I am hoping that the documentation in BLAZORHERO keeps pace with the project and we can follow it, step by step.
For example, I need to use Sendgrid in my project. I am used to using it in different way and would be grateful for steps on how to configure SENDGRID in BLAZORHERO. I don't even know which project to add the Sendgrid NUGET package into, how sad is that? :) :)
Many thanks
Luke

**Comment by Duelbat** [comment]
Thanks, but I love my Blazor and C#. Angular will give me nightmares  :)

**Comment by iang0ld** [comment]
Agreed.

**Comment by iang0ld** [comment]
It’s the back-end that is interesting.

**Comment by scottkuhl** [comment]
Documentation already exists here but developers will always have more questions and requests. The initial question about SendGrid is a good example.  This Issue is a large feature request that needs a lot more definition on what the documentation for this repo should look like.

Since this is currently the oldest open issue, I think it needs a path forward to get traction.  I think what is needed is an outline of what documentation is needed.

What does everything think is the best way forward for that:

1. Changing the Wiki to not point directly to code and use GitHub Wiki?
2. Start a Project Board just for documentation?
3. Just opening a bunch of specific documentation issues as a third option to Bug and Feature on new issues?

Since these would required some GitHub repo changes, I think we need @iammukeshm to weigh in.

Other ideas?

**Comment by Duelbat** [comment]
Yes, this is a beautiful template and thanks to Mukesh for that. However, as you point out Scottkuhl, if there is no adequate docs then wading through everything just takes too much time and I end up doing my own thing so that I know what I am doing. The creators of Templates do tend to think that their target audience are seasoned developers. But I have no clue as to how to get SENDGRID up and running in Blazorhero, yet I am using it just fine in my own app. Without great docs, I feel these templates will appeal to seasoned devs only and this is a shame as learning from them would be of great value.  - Note to MUKESH..... I would happily buy you 5 coffees for Sendgrid implementation in your Template !!   :)  :)

**Comment by scottkuhl** [comment]
@Duelbat perhaps you should open a new issue specifically for adding SendGrid support as a configurable option?  This issue seems more about documentation in general.  I would think other developers would want a SendGrid option as well since it is very popular.

**Comment by iammukeshm** [comment]
@Duelbat - Pointing out to  your requirement, I wrote in a few lines that can help you in the correct direction.

Since `Email Services` are potentially to be shared across various other layers and the fact that is more of a infrastructure concern, it's ideal to place it in the `BlazorHero.CleanArchitecture.Infrastructure.Shared` Layer, where you can already find `SMTPMailService` that's functional for SMTP Mails.

You could add a new class here, `SendGridMailService` that implements the `IMailService` interface. Of course, there can be changes required to the MailRequest DTO class as per your requirement.

Now, we need to be able to read the APIKey from the appsettings.json. For SMTP, we have used IOptions pattern to read the configuration-related data. Similarly, you can add another class named `SendGridConfiguration` to the BlazorHero.CleanArchitecture.Application layer under the Configuration folder with a property APIKey. You get the point, yeah?

Next, register this configuration class in the Startup.cs of the server project. Here - `BlazorHero.CleanArchitecture.Server.Extensions` / `AddSharedInfrastructure` method.
The needed code will be somewhat like this,
`services.Configure<SendGridConfiguration>(configuration.GetSection("SendGridConfiguration"));`

With the done, add your configuration to the appsettings.json under a new node SendGridConfiguration. This is the data we will be accessing via IOptions pattern.

Finally, all you have to do is to add in the Client Functionally of SendGrid in the `SendGridMailService` class, which I believe you are already familiar with.

Do not forget to register this service within the container as well. You can find it in the `BlazorHero.CleanArchitecture.Server.Extensions` / `AddSharedInfrastructure` method.
Add something like
`services.AddTransient<IMailService, SendGridMailService>();`

That should be it, you can start using an injected `IMailService` throughout your application to send out messages via SendGrid.

**Comment by iammukeshm** [comment]
@scottkuhl & @Duelbat , I totally agree. Yes, the current documentations are mostly setup-related only. I would attribute this issue to be more of my `not finding enough time` issue. However, as you suggested, I have opened up a new request on the repo that can allow devs to send in documentation request, which should be more effective. My feeling was that the idea of the architecture is the only requirement to add in the new features of the application. This project is mostly inspired from eshop series of Microsoft, which is quite self explanatory. I also have a complete guide to understand hex architecture, that should probably make it very easy to understand this implementation. But, yeah I can understand the concern. I hope the sendGrid comment that I wrote earlier, should help.

Regards
